### ISSUE TITLE
「商用利用可能」とライセンスについて

### ISSUE THREAD

**Issue by EaGitro** [dninomiya/tool-hub#4]
# 「商用利用可能」とライセンスについて

タグに `available-for-commercial-use`(商用利用可能) があると思います。

一口に商用利用可能と言っても、著作権を放棄しているものや種々のクリエイティブ・コモンズ・ライセンス、MIT のようなものなど幅広くあると思います。(著作権表示がいるか否か、ライセンスを明記する必要があるか等)

そこでこれは私の勝手なアイデアなのですが、`available-for-commercial-use` 以外にも何かライセンスを表すものをつけてはいかがでしょうか。そうすれば皆さん安心して使えると思います。

# 具体例

個人的には 1 の「タグとして記載する」がいいと思います。   
(リポジトリ主さんも「タグは良しなに追加してOK」とおっしゃっていましたし)

ですがあまり多くなってしまってはとも思います。(#3 でもMITタグの追加はしませんでした。)

## 1. タグとして記載する

そのままライセンス用のタグを作成する。 `available-for-commercial-use` と併用する形にする。

タグの例)
`Public-Domain`, `MIT-License`, `CC BY-ND 4.0`, `CC BY-SA 4.0` 等

### 利点
- シンプルで実装しやすい
- UI を壊すことがない
- ライセンス別でフィルタをかけることができる

### 難点
- タグが氾濫してしまう

## 2. 「商用利用可能」のタグをhoverするとライセンスが表示される  

「商用利用可能」のタグをマウスオーバーすると、ライセンスが表示されるようにする。

### 利点
- タグが氾濫しない

### 難点
- 実装が大変
- 見たところ radix を使われているようだが、実装によってはUIが見にくくなってしまうこともある
- データ構造が変わってしまう
  - 今までのデータと整合性を保つのが難しい

**Comment by dninomiya** [comment]
ご提案ありがとうございます！ 😎

いただいたご提案、大賛成なのでライセンスのタグを追加しました。シンプルイズベストということで、今後も必要に応じ適宜タグを増やす方向で解決できればと思います。（気軽に追加してもらってOKです）

今後も、お気づきの点あれば気軽にご提案ください！

**Comment by dninomiya** [comment]
ついでに、「無料素材についてはライセンス表記必要だが有料のものは不要」や、「無料のものは商用利用不可」、「イラストはXだがアイコンはN」など、同じサイトでも一概にライセンス表記や無料、商用利用のバッジをつけかねるシーンもありそうですね。

サイトとしては以下の対応が考えられます。

A. 実際には利用前にリンク先のライセンスページを確認するよう注釈を入れる（フッターなど。ただやや丸投げ感はある）
B. タグを増やす（「有料プランはライセンス表記不要」タグなど。ただ、タグが無限に増えそう）
C. 無料素材を基準にタグ付けするよう運用ルールを明文化（無料素材がライセンス表記不要であればそのタグを使える、など）

個人的には C が落とし所な気がしますが、他に良いアイデアあればぜひ！

背景：
有料素材はまず商用利用、ライセンス表記不要であるためあえて基準にする意味がない
商用利用、ライセンス表記の有無が分かれるのは一般的に無料素材の場合なので、そちらを軸にタグ付けするルールが良さそう

**Comment by EaGitro** [comment]
ありがとうございます。

確かに自分もCがいいと思います!     
加えて A も一応ユーザに対して、デザインの邪魔にならない程度に提示しておくと親切な感じはするかもしれないです。(個人開発などであまりライセンスに不慣れなユーザもいると考えられるので)

****

それとあれから再度考えたのですが、      

**ライセンスに不慣れなユーザ** ということを考えると、

- ライセンスベースのタグ付け

以外にも

- 「著作権表示必要/不要」「改変禁止/可能」「ライセンスを継承する必要/必要なし」というような **禁止される行為ベース or 許可された行為ベース** でのタグ付け
  - (もしこちらの方針を採用するなら「許可」か「禁止」のどちらをタグとして採用するかは統一すべきでしょう)

という選択肢もあるのかもしれません。(例えばすでにある `ライセンス表記不要` は上記にあたると思います。)

(例えば`CC BY-ND` なら「改変禁止」、`GPL`, `CC BY-SA` なら「ライセンス継承」等。ユーザがライセンスを知らなくても守るべきことがわかる)     

でも正直、ここまではこのアプリの責任範囲かというと微妙なところではあります。

どちらの方針で決めたとしても、両方のルールでタグを作るということさえしなければ、タグはせいぜい増えて数個でしょうし、   
リポジトリ主さんの好きな方でいいのかなと思っています。(なんか勝手にすみません...)

**Comment by dninomiya** [comment]
ありがとうございます！ユーザーとしては著作権表記不要、ライセンス継承必要なし、改変可能、など許可ベースで絞り込みたいシーンが多いと思うので、

- 改変可能
- ライセンス継承不要

を新たに追加しました。また、サイトによっては GPL などの定義ではなく、文言として許可/禁止が列挙されているシーンもあるので汎用性的にも許可ベースのタグ追加はGoodアイデアだと思います。

注釈も追加しました！ https://github.com/dninomiya/tool-hub/compare/631f442321c2763498e492db275c549e9ed5b751...main

ご提案ありがとうございます！ ⛱️

**Comment by dninomiya** [comment]
https://github.com/dninomiya/tool-hub/compare/631f442321c2763498e492db275c549e9ed5b751...main
